
server:
  port: 9898

jwt:
  secret: clanetest

spring:
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    #url: jdbc:postgresql://localhost:5432/postgres
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false